'use strict';
const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
const { sha256 } = require('./util');

// Read page dimensions (used by the field-placement UI and for coordinate mapping).
async function getPageSizes(bytes) {
  const pdf = await PDFDocument.load(bytes, { ignoreEncryption: true });
  return pdf.getPages().map((p) => ({ width: p.getWidth(), height: p.getHeight() }));
}

/**
 * Build the final signed PDF by stamping each field's value onto the page, then
 * appending a Certificate of Completion. Field positions are stored as fractions
 * (xPct/yPct from the TOP-LEFT, wPct/hPct of page size) so they map cleanly
 * regardless of the zoom the signer used.
 */
async function generateSignedPdf({ originalBytes, doc, recipients, fields }) {
  const pdf = await PDFDocument.load(originalBytes, { ignoreEncryption: true });
  const pages = pdf.getPages();
  const helv = await pdf.embedFont(StandardFonts.Helvetica);
  const helvB = await pdf.embedFont(StandardFonts.HelveticaBold);

  for (const f of fields) {
    const page = pages[f.page];
    if (!page || f.value == null || f.value === '' || f.value === false) continue;
    const pw = page.getWidth();
    const ph = page.getHeight();
    const x = pw * f.xPct;
    const w = pw * f.wPct;
    const h = ph * f.hPct;
    const y = ph - ph * f.yPct - h; // convert top-left origin -> pdf bottom-left

    if ((f.type === 'signature' || f.type === 'initials') && String(f.value).startsWith('data:image')) {
      try {
        const png = await pdf.embedPng(Buffer.from(String(f.value).split(',')[1], 'base64'));
        const ar = png.width / png.height;
        let dw = w, dh = w / ar;
        if (dh > h) { dh = h; dw = h * ar; }
        page.drawImage(png, { x: x + (w - dw) / 2, y: y + (h - dh) / 2, width: dw, height: dh });
      } catch (e) { /* skip unreadable image */ }
    } else if (f.type === 'checkbox') {
      if (f.value === true || f.value === 'true' || f.value === 'on') {
        page.drawText('X', { x: x + 1, y: y + 1, size: Math.min(h, 16), font: helvB, color: rgb(0.1, 0.1, 0.1) });
      }
    } else {
      const size = Math.max(8, Math.min(13, h * 0.62));
      page.drawText(String(f.value), { x: x + 2, y: y + (h - size) / 2 + 1, size, font: helv, color: rgb(0.06, 0.09, 0.25) });
    }
  }

  addCertificate(pdf, helv, helvB, { doc, recipients, hash: sha256(originalBytes) });
  return Buffer.from(await pdf.save());
}

function fmt(s) {
  if (!s) return '—';
  try { return new Date(s).toUTCString(); } catch (e) { return String(s); }
}

function addCertificate(pdf, helv, helvB, { doc, recipients, hash }) {
  const page = pdf.addPage([612, 792]); // US Letter
  const left = 50;
  let y = page.getHeight() - 60;

  const text = (s, o = {}) => {
    page.drawText(String(s), { x: o.x || left, y, size: o.size || 10, font: o.bold ? helvB : helv, color: o.color || rgb(0.12, 0.12, 0.16) });
    y -= o.gap || 16;
  };

  page.drawText('Certificate of Completion', { x: left, y, size: 19, font: helvB, color: rgb(0.12, 0.16, 0.42) });
  y -= 14;
  page.drawLine({ start: { x: left, y }, end: { x: 562, y }, thickness: 1, color: rgb(0.85, 0.87, 0.92) });
  y -= 22;

  text(`Document: ${doc.title}`, { bold: true });
  text(`Document ID: ${doc.id}`);
  text(`Status: ${doc.status}`);
  text(`Created: ${fmt(doc.createdAt)}`);
  text(`Completed: ${fmt(doc.completedAt)}`);
  text(`Original document SHA-256:`, { gap: 12 });
  text(hash, { size: 8, color: rgb(0.4, 0.4, 0.45), gap: 22 });

  text('Signers', { bold: true, size: 13, gap: 20 });
  recipients.forEach((r, i) => {
    text(`${i + 1}.  ${r.name}  <${r.email}>`, { bold: true });
    text(`     Status: ${r.status}    Signed: ${fmt(r.signedAt)}`, { size: 9, color: rgb(0.3, 0.3, 0.35) });
    text(`     IP address: ${r.signedIp || '—'}`, { size: 9, color: rgb(0.3, 0.3, 0.35) });
    if (r.declineReason) text(`     Decline reason: ${r.declineReason}`, { size: 9, color: rgb(0.6, 0.1, 0.1) });
    y -= 6;
  });

  y = Math.max(y, 70);
  page.drawText('This certificate records the electronic signing of the document identified above, including signer',
    { x: left, y, size: 8, font: helv, color: rgb(0.5, 0.5, 0.55) });
  page.drawText('identities, timestamps (UTC), and originating IP addresses. Generated by DeoDap eSign.',
    { x: left, y: y - 11, size: 8, font: helv, color: rgb(0.5, 0.5, 0.55) });
}

module.exports = { getPageSizes, generateSignedPdf };
